config/routes.rb
Rails.application.routes.draw do

  resources :games do
    member do
      get 'index'
      post 'create'
      get 'show'
      post 'answer'
    end
  end

  root 'pages#home'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :inputs, dependent: :destroy
	accepts_nested_attributes_for :inputs

	after_create :create_inputs

	NECESSARY_FREQUENCY = 0.5
	SUFFICIENT_FREQUENCY = 0.1
	NUM_INPUTS = 3
	EVIDENCE_FRACTION = 1

	def create_inputs
		NUM_INPUTS.times do 
			Input.create!(game_id: self.id, necessary: (rand < NECESSARY_FREQUENCY), sufficient: (rand < SUFFICIENT_FREQUENCY))
		end

		self.enforce_input_consistency
	end

	def enforce_input_consistency
		if self.inputs.detect{|i| i.sufficient == true}
			self.inputs.map do |i| 
				if i.necessary && !i.sufficient
					i.necessary = false
					i.save
				end
			end
		end
	end

	# How we get from input to output.
	# What happens, when none is necessary, and none is sufficient?
	def output_on(input_statuses)
		input_statuses.each_with_index do |input_on, i|
			actual_input = inputs[i]
			if actual_input.sufficient && input_on
				return true
			elsif actual_input.necessary && !input_on
				return false
			end
		end
		return input_statuses.count{|i| i == true} >= 2
	end

	def all_evidence
		all_results = []
		(0..NUM_INPUTS).each do |i|
			seed_arr = []
			i.times do
				seed_arr.push(false)
			end
			(NUM_INPUTS - i).times do
				seed_arr.push(true)
			end
			all_results.push(seed_arr.permutation.to_a.uniq)
		end
		all_results.flatten(1)
	end

	def random_subset_of_evidence
		all_evidence.sample((all_evidence.length * EVIDENCE_FRACTION).floor)
	end

	def random_subset_of_evidence_with_result
		random_subset_of_evidence.map{|arr| arr + [output_on(arr)]}
	end

end

app/models/input.rb
class Input < ActiveRecord::Base
	belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def create
  end

  def show
  end

  def answer
  	@game = Game.find(params[:id])
  	@is_correct = true
  	@game.inputs.each_with_index do |input, i|
  		if input.necessary && params[:game][:inputs_attributes][i.to_s][:necessary] != "1"
  			@is_correct = false
  			break
  		elsif input.sufficient && params[:game][:inputs_attributes][i.to_s][:sufficient] != "1"
  			@is_correct = false
  			break
  		end
  	end
  	@is_correct

  	@evidence_sets = @game.random_subset_of_evidence_with_result
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@game = Game.create!
  	@evidence_sets = @game.random_subset_of_evidence_with_result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_game.html.erb
<% game.inputs.each do |input| %>
<div><%= input.necessary %></div>
<div><%= input.sufficient %></div>
<% end %>

<%= form_for game, url: answer_game_path(game), method: :post do |f| %>
	<%= f.fields_for :inputs do |builder| %>
		<fieldset>
	  	<%= builder.label :necessary, "Necessary" %>
	  	<%= builder.check_box :necessary, checked: false %>
	  	<%= builder.label :sufficient, "Sufficient" %>
	  	<%= builder.check_box :sufficient, checked: false %>
		</fieldset>
	<% end %>
  <%= f.submit "Create" %>
<% end %>

<p>EVIDENCE</p>
<% evidence_sets.each do |evidence_set| %>
	<div class="evidence-set">
		<div class="input-bulbs">
			<% (0...Game::NUM_INPUTS).each do |i| %>
				<div class="input-bulb <%= 'active' if evidence_set[i] %>"></div>
			<% end %>
		</div>
		<div class="output-bulb <%= 'active' if evidence_set[Game::NUM_INPUTS] %>"></div>
	</div>
<% end %>

app/views/games/answer.html.erb
<% if @is_correct %>
	<p>You got it! <%= link_to "Play again!", root_path %></p>
<% else %>
	<p>Incorrect, sorry. Please try again.</p>
<% end %>

<p>Were you right? <%= @is_correct %></p>
<%= render partial: 'games/game', locals: { game: @game, evidence_sets: @evidence_sets } %>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NecessarySufficient</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<p>INPUT IDENTITIES</p>
<% @game.inputs.each do |input| %>
<div>
	<%= input.necessary %>
	<%= input.sufficient %>
</div>
<% end %>

<p>EVIDENCE</p>
<% @evidence_sets.each do |evidence_set| %>
	<div class="evidence-set">
		<div class="input-bulbs">
			<% (0...Game::NUM_INPUTS).each do |i| %>
				<div class="input-bulb <%= 'active' if evidence_set[i] %>"></div>
			<% end %>
		</div>
		<div class="output-bulb <%= 'active' if evidence_set[Game::NUM_INPUTS] %>"></div>
	</div>
<% end %>